#!/usr/bin/env python

import rospy
import time
import numpy as np
import os, string
import cv2, cv
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image


class image_sender:
	def __init__(self):

		#cv_image = bridge.imgmsg_to_cv(image_message, desired_encoding="passthrough")
		self.im_pub = rospy.Publisher('Camera', Image)
		self.bridge = CvBridge()	

	
	def send_message(self, cv_image):
		try:
			image_message = self.bridge.cv_to_imgmsg(cv.fromarray(cv_image),"bgr8")#,desired_encoding="passthrough")
			self.im_pub.publish(image_message)
		except CvBridgeError, e:
			print e

	
def main():
	imsend = image_sender()
	rospy.init_node('camera')
	
	cam = cv2.VideoCapture(0)	

	targetResolution = (640,360)
	#targetResolution = (960,720)
	cam.set(3,targetResolution[0]) #Width
	cam.set(4,targetResolution[1]) #Height
	

	while not rospy.is_shutdown():	
		try:
			ret, frame = cam.read()
			if(ret):
				#rospy.loginfo(frame.shape)
					
				imsend.send_message(frame)
			else:

				rospy.loginfo("FAIL Camera Read")
			#rospy.sleep(0.5)
			#rospy.spin()
		except KeyboardInterrupt:
			print "Shutting Down"
if __name__ == '__main__':
	main()

